import Head from "next/head";
import { Inter } from "next/font/google";
import { supabase } from "@/utils/supabaseClient";
import { useContext, useState } from "react";
import { AuthContext, AuthInfo } from "@/context/auth";
const inter = Inter({ subsets: ["latin"] });

export default function Home(): any {
  return (
    <>
      <Head>
        <title>TOKOTOKO=J</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>

        </div>
        <div className="table">
        </div>
      </div>
    </>
  );
}
