export const jLeagueTeams = [
  { label: 'CerezoOsaka', name: 'セレッソ大阪', league: 'J1リーグ', img: "/teamUniform/osaka_s.png", stadium: 'ヤンマースタジアム長居' },
  { label: 'KashimaAntlers', name: '鹿島アントラーズ', league: 'J1リーグ', img: "/teamUniform/kashima.png", stadium: 'カシマサッカースタジアム' },
  { label: 'UrawaRedDiamonds', name: '浦和レッズ', league: 'J1リーグ', img: "/teamUniform/urawa.png", stadium: '埼玉スタジアム2002' },
  { label: 'KashiwaReysol', name: '柏レイソル', league: 'J1リーグ', img: "/teamUniform/kashiwa.png", stadium: 'フクダ電子アリーナ' },
  { label: 'FCTokyo', name: 'FC東京', league: 'J1リーグ', img: "/teamUniform/tokyo.png", stadium: '味の素スタジアム' },
  { label: 'KawasakiFrontale', name: '川崎フロンターレ', league: 'J1リーグ', img: "/teamUniform/kawasaki.png", stadium: '等々力陸上競技場' },
  { label: 'YokohamaFMarinos', name: '横浜F・マリノス', league: 'J1リーグ', img: "/teamUniform/yokohama.png", stadium: '日産スタジアム' },
  { label: 'ShonanBellmare', name: '湘南ベルマーレ', league: 'J1リーグ', img: "/teamUniform/shonan.png", stadium: 'Shonan BMW スタジアム平塚' },
  { label: 'YokohamaFC', name: '横浜FC', league: 'J1リーグ', img: "/teamUniform/yokohama.png", stadium: 'ニッパツ三ツ沢球技場' },
  { label: 'AlbirexNiigata', name: 'アルビレックス新潟', league: 'J1リーグ', img: "/teamUniform/yokohama.png", stadium: 'デンカビッグスワンスタジアム' },
  { label: 'NagoyaGrampus', name: '名古屋グランパス', league: 'J1リーグ', img: "/teamUniform/nagoya.png", stadium: 'パロマ瑞穂スタジアム' },
  { label: 'KyotoSangaFC', name: '京都サンガF.C.', league: 'J1リーグ', img: "/teamUniform/kyoto.png", stadium: '京都市西京極総合運動公園陸上競技場' },
  { label: 'GambaOsaka', name: 'ガンバ大阪', league: 'J1リーグ', img: "/teamUniform/osaka_g.png", stadium: 'パナソニックスタジアム吹田' },
  { label: 'VisselKobe', name: 'ヴィッセル神戸', league: 'J1リーグ', img: "/teamUniform/kode.png", stadium: 'ノエビアスタジアム神戸' },
  { label: 'SanfrecceHiroshima', name: 'サンフレッチェ広島', league: 'J1リーグ', img: "/teamUniform/hiroshima.png", stadium: 'エディオンスタジアム広島' },
  { label: 'AvispaFukuoka', name: 'アビスパ福岡', league: 'J1リーグ', img: "/teamUniform/fukuoka.png", stadium: 'ベストアメニティスタジアム' },
  { label: 'SaganTosu', name: 'サガン鳥栖', league: 'J1リーグ', img: "/teamUniform/tosu.png", stadium: 'ベストアメニティスタジアム' },
  { label: 'BlaublitzAkita', name: 'ブラウブリッツ秋田', league: 'J2リーグ', img: "/teamUniform/shimizu.png", stadium: '秋田市八橋陸上競技場' },
  { label: 'MontedioYamagata', name: 'モンテディオ山形', league: 'J2リーグ', img: "/teamUniform/sapporo.png", stadium: 'NDソフトスタジアム山形' },
];



export const studiumsData = [
  { label: 'ヤンマースタジアム長居', name: 'ヤンマースタジアム長居', img: "/teamUniform/osaka_s.png" },
  { label: 'カシマサッカースタジアム', name: 'カシマサッカースタジアム', img: "/teamUniform/kashima.png" },
  { label: '埼玉スタジアム2002', name: '埼玉スタジアム2002', img: "/teamUniform/urawa.png" },
  { label: 'フクダ電子アリーナ', name: 'フクダ電子アリーナ', img: "/teamUniform/kashiwa.png" },
  { label: '味の素スタジアム', name: '味の素スタジアム', img: "/teamUniform/tokyo.png" },
  { label: '等々力陸上競技場', name: '等々力陸上競技場', img: "/teamUniform/kawasaki.png" },
  { label: '日産スタジアム', name: '日産スタジアム', img: "/teamUniform/yokohama.png" },
  { label: 'Shonan BMW スタジアム平塚', name: 'Shonan BMW スタジアム平塚', img: "/teamUniform/shonan.png" },
  { label: 'ニッパツ三ツ沢球技場', name: 'ニッパツ三ツ沢球技場', img: "/teamUniform/yokohama.png" },
  { label: 'デンカビッグスワンスタジアム', name: 'デンカビッグスワンスタジアム', img: "/teamUniform/yokohama.png" },
  { label: 'パロマ瑞穂スタジアム', name: 'パロマ瑞穂スタジアム', img: "/teamUniform/nagoya.png" },
  { label: '京都市西京極総合運動公園陸上競技場', name: '京都市西京極総合運動公園陸上競技場', img: "/teamUniform/kyoto.png" },
  { label: 'パナソニックスタジアム吹田', name: 'パナソニックスタジアム吹田', img: "/teamUniform/osaka_g.png" },
  { label: 'ノエビアスタジアム神戸', name: 'ノエビアスタジアム神戸', img: "/teamUniform/kode.png" },
  { label: 'エディオンスタジアム広島', name: 'エディオンスタジアム広島', img: "/teamUniform/hiroshima.png" },
  { label: 'ベストアメニティスタジアム', name: 'ベストアメニティスタジアム', img: "/teamUniform/fukuoka.png" },
  { label: 'NDソフトスタジアム山形', name: 'NDソフトスタジアム山形', img: "/teamUniform/sapporo.png" },
  { label: '秋田市八橋陸上競技場', name: '秋田市八橋陸上競技場', img: "/teamUniform/shimizu.png" },
  { label: 'ユアテックスタジアム仙台', name: 'ユアテックスタジアム仙台', img: "/teamUniform/sendai.png" },
  { label: 'ノエビアスタジアム神戸', name: 'ノエビアスタジアム神戸', img: "/teamUniform/kode.png" },
  { label: 'ベストアメニティスタジアム', name: 'ベストアメニティスタジアム', img: "/teamUniform/fukuoka.png" },
  { label: 'ヤンマースタジアム長居', name: 'ヤンマースタジアム長居', img: "/teamUniform/osaka_s.png" },

]