export const jLeagueTeams = [
  { label: 'CerezoOsaka', name: 'セレッソ大阪', league: 'J1リーグ', img: "/osaka_s.png", stadium: 'ヤンマースタジアム長居' },
  { label: 'KashimaAntlers', name: '鹿島アントラーズ', league: 'J1リーグ', img: "/kashima.png", stadium: 'カシマサッカースタジアム' },
  { label: 'UrawaRedDiamonds', name: '浦和レッズ', league: 'J1リーグ', img: "/urawa.png", stadium: '埼玉スタジアム2002' },
  { label: 'KashiwaReysol', name: '柏レイソル', league: 'J1リーグ', img: "/kashiwa.png", stadium: 'フクダ電子アリーナ' },
  { label: 'FCTokyo', name: 'FC東京', league: 'J1リーグ', img: "/tokyo.png", stadium: '味の素スタジアム' },
  { label: 'KawasakiFrontale', name: '川崎フロンターレ', league: 'J1リーグ', img: "/kawasaki.png", stadium: '等々力陸上競技場' },
  { label: 'YokohamaFMarinos', name: '横浜F・マリノス', league: 'J1リーグ', img: "/yokohama.png", stadium: '日産スタジアム' },
  { label: 'ShonanBellmare', name: '湘南ベルマーレ', league: 'J1リーグ', img: "/shonan.png", stadium: 'Shonan BMW スタジアム平塚' },
  { label: 'YokohamaFC', name: '横浜FC', league: 'J1リーグ', img: "/yokohama.png", stadium: 'ニッパツ三ツ沢球技場' },
  { label: 'AlbirexNiigata', name: 'アルビレックス新潟', league: 'J1リーグ', img: "/yokohama.png", stadium: 'デンカビッグスワンスタジアム' },
  { label: 'NagoyaGrampus', name: '名古屋グランパス', league: 'J1リーグ', img: "/nagoya.png", stadium: 'パロマ瑞穂スタジアム' },
  { label: 'KyotoSangaFC', name: '京都サンガF.C.', league: 'J1リーグ', img: "/kyoto.png", stadium: '京都市西京極総合運動公園陸上競技場' },
  { label: 'GambaOsaka', name: 'ガンバ大阪', league: 'J1リーグ', img: "/osaka_g.png", stadium: 'パナソニックスタジアム吹田' },
  { label: 'VisselKobe', name: 'ヴィッセル神戸', league: 'J1リーグ', img: "/kode.png", stadium: 'ノエビアスタジアム神戸' },
  { label: 'SanfrecceHiroshima', name: 'サンフレッチェ広島', league: 'J1リーグ', img: "/hiroshima.png", stadium: 'エディオンスタジアム広島' },
  { label: 'AvispaFukuoka', name: 'アビスパ福岡', league: 'J1リーグ', img: "/fukuoka.png", stadium: 'ベストアメニティスタジアム' },
  { label: 'SaganTosu', name: 'サガン鳥栖', league: 'J1リーグ', img: "/tosu.png", stadium: 'ベストアメニティスタジアム' },
  { label: 'BlaublitzAkita', name: 'ブラウブリッツ秋田', league: 'J2リーグ', img: "/shimizu.png", stadium: '秋田市八橋陸上競技場' },
  { label: 'MontedioYamagata', name: 'モンテディオ山形', league: 'J2リーグ', img: "/sapporo.png", stadium: 'NDソフトスタジアム山形' },
];
