export const jLeagueTeams = [
  { label: 'Cerezo Osaka', name: 'セレッソ大阪', league: 'J1リーグ',img:"/osaka_s.png" },
  { label: 'Kashima Antlers', name: '鹿島アントラーズ', league: 'J1リーグ',img:"/kashima.png"  },
  { label: 'Urawa Red Diamonds', name: '浦和レッズ', league: 'J1リーグ',img:"/urawa.png"  },
  { label: 'Kashiwa Reysol', name: '柏レイソル', league: 'J1リーグ',img:"/kashiwa.png"  },
  { label: 'FC Tokyo', name: 'FC東京', league: 'J1リーグ',img:"/tokyo.png"  },
  { label: 'Kawasaki Frontale', name: '川崎フロンターレ', league: 'J1リーグ',img:"/kawasaki.png"  },
  { label: 'Yokohama F. Marinos', name: '横浜F・マリノス', league: 'J1リーグ',img:"/yokohama.png"  },
  { label: 'Shonan Bellmare', name: '湘南ベルマーレ', league: 'J1リーグ',img:"/shonan.png"  },
  { label: 'Yokohama FC', name: '横浜FC', league: 'J1リーグ',img:"/yokohama.png"  },
  { label: 'Albirex Niigata', name: 'アルビレックス新潟', league: 'J1リーグ',img:"/yokohama.png"  },
  { label: 'Nagoya Grampus', name: '名古屋グランパス', league: 'J1リーグ',img:"/nagoya.png"  },
  { label: 'Kyoto Sanga F.C.', name: '京都サンガF.C.', league: 'J1リーグ',img:"/kyoto.png"  },
  { label: 'Gamba Osaka', name: 'ガンバ大阪', league: 'J1リーグ',img:"/osaka_g.png"  },
  { label: 'Vissel Kobe', name: 'ヴィッセル神戸', league: 'J1リーグ',img:"/kode.png"  },
  { label: 'Sanfrecce Hiroshima', name: 'サンフレッチェ広島', league: 'J1リーグ',img:"/hiroshima.png"  },
  { label: 'Avispa Fukuoka', name: 'アビスパ福岡', league: 'J1リーグ',img:"/fukuoka.png"  },
  { label: 'Sagan Tosu', name: 'サガン鳥栖', league: 'J1リーグ',img:"/tosu.png"  },
  { label: 'Blaublitz Akita', name: '清水エスパルス', league: 'J2リーグ', img:"/shimizu.png"  },
  { label: 'Montedio Yamagata', name: 'コンサドーレ札幌', league: 'J2リーグ', img:"/sapporo.png"  },
];
